### ISSUE TITLE
Preserve small range radio settings after respawn

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/Shoot_and_Scoot.Tanoa#17]

**Comment by b-mayr-1984** [comment]
@DerZade how do I do that?

**Comment by nomisum** [comment]
> @DerZade how do I do that?
> 
> 

there is a fnc in tvt template, look under linearSD.

**Comment by DerZade** [comment]
I think @McDiod did it in Linear Sector defense 🤔

But I would guess: Read and save the settings in a Killed Event handler and then apply them in a respawn event handler.

**Comment by McDiod** [comment]
This is just a bunch of eventhandlers - you can run it almost as-is:

https://github.com/gruppe-adler/TvT_Template.VR/blob/master/functions/linearSD/fn_transferRadiosAcrossRespawn.sqf

The other option is to reuse the radio ID on respawn (e.g. the "5" in "TF_anprc152_5") as seen in GameOfGuns.

**Comment by b-mayr-1984** [comment]
@McDiod should I be worried about this error message showing up in my RPT log after implementing your event handlers?

```
22:32:12 Error in expression <e _result = [];

_result pushBackUnique _overrideLR; 
if (_activeLR isEqualTo _v>
22:32:12   Error position: <_overrideLR; 
if (_activeLR isEqualTo _v>
22:32:12   Error Undefined variable in expression: _overridelr
22:32:12 File z\tfar\addons\core\functions\fnc_lrRadiosList.sqf..., line 35
```

Even thoug this error is thrown I still get persistent settings (for both SR and LR radios).

**Comment by nomisum** [comment]
iirc had the same issue but works
