### ISSUE TITLE
Order of obj. markers

### ISSUE THREAD

**Issue by DerZade** [gruppe-adler/Shoot_and_Scoot.Tanoa#18]
Please order the obj markers somehow. It's just a pain to find a objective when someone calls "Red -5" or something similar.

You could do name them:
- from from east (1) to west (20)
- from west (1) to east (20)
- by rough-grid reference (the most milsimy and my preferred method, but names are a bit longer `Blue-57-73`)

**Comment by b-mayr-1984** [comment]
> Please order the obj markers somehow. It's just a pain to find a objective when someone calls "Red -5" or something similar.

I totally agree with the pain. It even bothers me as Zeus, when placing the containers. 😅 

 
> You could do name them:
> 
> * from from east (1) to west (20)
> * from west (1) to east (20)
> * by rough-grid reference (the most milsimy and my preferred method, but names are a bit longer `Blue-57-73`)

I went with option 3. 
It is easiest to then shift markers around without affecting other markers in terms of their numbering.
![image](https://user-images.githubusercontent.com/76476468/236570383-3e728a10-86b1-4d0f-9724-36f530ea6b73.png)

**Comment by b-mayr-1984** [comment]
In the debriefing to the [last game night](https://forum.gruppe-adler.de/topic/3168/2023-07-10-mo-tvt-shoot-and-scoot-joint-ops-only-no-gm-2402) players complained about the new marker names being to tedious to communicate over the radio.

So option 2 from the initial request will be implemented.
> * from west (1) to east (20)

**Comment by b-mayr-1984** [comment]
A script will now automatically sort the markers and rename them from West to East.
![image](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/76476468/6924469e-9ecf-4805-b28b-7e4511322f8f)
