### ISSUE TITLE
UAV jammer

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/Shoot_and_Scoot.Tanoa#26]
In order to closer resemble aspects of modern conflicts 
and to add more depth to tactical decision making 
adding a **counter UAV electromagnetic jammer** would be a nice feature.

A plausible plattform for the jammer could be the Radar Wiesel, because it comes with a transceiver that can be turned on and off out of the box.
![image](https://static.wikia.nocookie.net/armedassault/images/2/2a/Arma3-render-nyxrecondigitalgreen.png/revision/latest?cb=20190816092657)

Whilst being jammed a drone 
- should stop moving and be unable to move any further ([disableAI ](https://community.bistudio.com/wiki/disableAI) "PATH").
  - alternatively a return-to-home could be triggered with a given altitude 
    - finding the pilot via [UAVControl](https://community.bistudio.com/wiki/UAVControl) and set a waypoint close to the pilot
    - setting RTH altitude via [flyInHeight](https://community.bistudio.com/wiki/flyInHeight) 
- its video transmission to the drone operator should not work anymore. So the turret needs to be rendered ineffective. A bunch of commands that could help achieve this are shown below:
  - [lockTurret](https://community.bistudio.com/wiki/lockTurret)
  - [setTurretLimits](https://community.bistudio.com/wiki/setTurretLimits)
  - [setTurretOpticsMode](https://community.bistudio.com/wiki/setTurretOpticsMode) (cycling through the modes to render the image useless)
  - [lockCameraTo](https://community.bistudio.com/wiki/lockCameraTo) (locking to a useless point in the sky)
 - The [Remote Control group of commands](https://community.bistudio.com/wiki/Category:Command_Group:_Remote_Control) should also be useful to simulate jamming effects. In particular:
   - `player connectTerminalToUAV objNull; //disconnect`

In order to locate active jammers one could use
- Radar warning receiver of larger drones (see also #19)
- [spectrum device](https://community.bistudio.com/wiki/Arma_3:_Spectrum_Device) from the Contact DLC (e.g. for the SQL of a hunter-killer team)
![image](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/76476468/aedf17c2-0368-4dfa-ac92-edcdfb8e538c)

Screenshot was created using:
```
missionNamespace setVariable ["#EM_FMin", 400]; 
missionNamespace setVariable ["#EM_FMax", 900];
missionNamespace setVariable ["#EM_SMin", -60]; 
missionNamespace setVariable ["#EM_SMax", -10];
missionNamespace setVariable ["#EM_SelMin", 450]; 
missionNamespace setVariable ["#EM_SelMax", 560];
missionNamespace setVariable ["#EM_Values", [481.8, -30, 675.85, -50, 785.12, -40]];
```

More information on the spectrum device in this video (and its description as well as comment section): 
- [ArmA 3 Editing : Spectrum Device Tracking](https://www.youtube.com/watch?v=yV0bOgaP5b4)

**Comment by NeutraleNull** [comment]
Maybe add a film grain to the cameras to "worsen" the view the closer the UAV gets to a jammer

**Comment by b-mayr-1984** [comment]
> Maybe add a film grain to the cameras to "worsen" the view the closer the UAV gets to a jammer

Sounds good. How do I do that? 🙂

**Comment by NeutraleNull** [comment]
i have not tried it but maybe this can lead to the right track https://forums.bohemia.net/forums/topic/184648-need-help-with-simple-script-to-create-constant-film-grain/

**Comment by MildlyInterested** [comment]
Mod that has a trackable jamming source that shows up in the spectrum device:
https://github.com/mjc4wilton/jsoc_ew
Different mod that lets you add trackable objects via zeus
https://github.com/Crowdedlight/Crows-Electronic-Warfare

Talked about it in teamspeak, putting it here so it's easier to find again.

**Comment by b-mayr-1984** [comment]
> Mod that has a trackable jamming source that shows up in the spectrum device: https://github.com/mjc4wilton/jsoc_ew Different mod that lets you add trackable objects via zeus https://github.com/Crowdedlight/Crows-Electronic-Warfare
> 
> Talked about it in teamspeak, putting it here so it's easier to find again.

Thanks, I will have a look at it. 🙂

**Comment by b-mayr-1984** [comment]
> i have not tried it but maybe this can lead to the right track https://forums.bohemia.net/forums/topic/184648-need-help-with-simple-script-to-create-constant-film-grain/

Perfect, thank you. 🤩 

This filter messes up the camera pretty well (example for a video feed being totally jammed)
```
PP_film = ppEffectCreate ["FilmGrain",2000]; 
PP_film ppEffectEnable true; 
PP_film ppEffectAdjust [1,0,3.3,2,2,false]; 
PP_film ppEffectCommit 0;
```

![image](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/76476468/88962170-4999-4e16-b6f3-161f1b7bd54c)

Partially effected video feed is also doable.
`PP_film ppEffectAdjust [1,0.8,3.3,2,2,false];`
![image](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/76476468/11695009-9065-4386-9947-e441ab2c3353)

`ppEffectDestroy PP_film;` restores the camera back to normal.

**Comment by b-mayr-1984** [comment]
> Mod that has a trackable jamming source that shows up in the spectrum device: https://github.com/mjc4wilton/jsoc_ew Different mod that lets you add trackable objects via zeus https://github.com/Crowdedlight/Crows-Electronic-Warfare
> 
> Talked about it in teamspeak, putting it here so it's easier to find again.

Thanks @MildlyInterested for the hint. 
After evaluation of these mods I think I will go with **Crows-Electronic-Warfare** and build upon that. 🙂

**Comment by b-mayr-1984** [comment]
At first the Wiesel from the initial post will **not** be implemented.
Instead there will be transportable jammer boxes that can be turned on and off using the vanilla action menu.
![image](https://cdn.discordapp.com/attachments/402412803153199104/1202531922098786335/image.png?ex=65cdcc20&is=65bb5720&hm=ac8674aebedf7e16bd3f35fe5b06f5a78eb992687304a4c05b87abc1e2c2013b&)

Adding the Wiesel would add the need for AT weapons which in turn changes the balance with regards to the MRAPs used by the mortar teams. For now I don't want to open this balancing can of worms.

**Comment by b-mayr-1984** [comment]
Implemented as part of the mod **Crows-Electronic-Warfare** (see https://github.com/Crowdedlight/Crows-Electronic-Warfare/pull/65)

(Test on Gruppe Adler infrastructure with multiple players not done yet.)

**Comment by b-mayr-1984** [comment]
> (Test on Gruppe Adler infrastructure with multiple players not done yet.)

Did such tests in the meantime with @PulsarNeutronStar and Drakenberger. 
The tests showed that there is still stabilization work to do with regards to JIP and locality issues.

See ongoing work/discussions at:
- https://github.com/Crowdedlight/Crows-Electronic-Warfare/pull/65#issuecomment-1962997194
- https://github.com/b-mayr-1984/Crows-Electronic-Warfare/pull/1

**Comment by b-mayr-1984** [comment]
> [..] tests showed that there is still stabilization work to do with regards to JIP and locality issues.
> 
> See ongoing work/discussions at:
> 
> * [Omni-directional CUAS jammer Crowdedlight/Crows-Electronic-Warfare#65 (comment)](https://github.com/Crowdedlight/Crows-Electronic-Warfare/pull/65#issuecomment-1962997194)
> * [WIP: Omni jammer patch b-mayr-1984/Crows-Electronic-Warfare#1](https://github.com/b-mayr-1984/Crows-Electronic-Warfare/pull/1)

Another test with hitbox_sandmann demonstrated that 
- JIP issues were fixed
- locality issues were mostly gone

After todays final changes in [WIP: Omni jammer patch b-mayr-1984/Crows-Electronic-Warfare#1](https://github.com/b-mayr-1984/Crows-Electronic-Warfare/pull/1) the remaining locality issues should be fixed now. Hopefully one final test run will confirm that.

**Comment by Crowdedlight** [comment]
I have published the latest release of EWAR which includes the PRs and all the new stuff. Once again thanks for the big work you put in to give this new functionality and fixes to the players! 

Also helped me actually getting some stuff rewritten so its easier to work with in the future and in a better state than before 😅

**Comment by b-mayr-1984** [comment]
> After todays final changes in [WIP: Omni jammer patch b-mayr-1984/Crows-Electronic-Warfare#1](https://github.com/b-mayr-1984/Crows-Electronic-Warfare/pull/1) the remaining locality issues should be fixed now. Hopefully one final test run will confirm that.

Confirmed fixed with todays test. 

Thx to @nomisum and @PulsarNeutronStar. 🙂
