### ISSUE TITLE
Camo Nets act as powerful shields

### ISSUE THREAD

**Issue by senshi-x** [gruppe-adler/Shoot_and_Scoot.Tanoa#29]
More of a vanilla Arma "bug", but I feel it's rather unexpected on this mission. The camo nets absorbs a surprisingly high amount of damage and prevents it from reaching the targets.
Most noticeable when using mortars: Direct hits with mortars on top of the camo net deal zero damage to the container underneath. The net is impermeable even to blast/indirect damage.

Only when hitting next to the cargo net there's a chance for the blast damage to "slip" underneath the net and actually hit the container.
Alternatively, it takes 4(!) direct mortar hits or at least  2 direct artillery hits to destroy/flatten the camo net, and only then will direct hits deal damage to the container as one would expect.

**Comment by b-mayr-1984** [comment]
> Alternatively, it takes 4(!) direct mortar hits or at least 2 direct artillery hits to destroy/flatten the camo net, and only then will direct hits deal damage to the container as one would expect.

Do you think setting the initial damage of the camo net to 90% [here](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/blob/82c6a40d12016184ec2b86d9a4ec9aa5130da431/scripts/spot-randomizer/functions/fn_placeSupplyStation.sqf#L49) would be an adequate fix?
