### ISSUE TITLE
Radio direction finder for TFAR emissions

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/Shoot_and_Scoot.Tanoa#36]
Similar to the bearing lines that show up upon artillery fire, bearing lines for TFAR radio emissions would be a nice and plausible addition. 
![](https://feedback.bistudio.com/file/data/2qstomsyevontjxpykb3/PHID-FILE-3ozflwmlbhbsz2dpkft2/bearing_lines_on_map.png)

Similar game mechanics are being introduced by the addition of [Crows-Electronic-Warfare](https://github.com/Crowdedlight/Crows-Electronic-Warfare) to the game mode. But those only work in connection with the [Spectrum Device](https://armedassault.fandom.com/wiki/Spectrum_device). This issue is about enabling the sensor trucks to show such bearings.

 - [x] Bearing lines should be visually different to bearing lines from artillery fire (e.g. different color)
 - [x] Bearings should show up instantly upon triggering the radio (e.g. no delay for the speed of sound)

**Comment by Crowdedlight** [comment]
Saw this one as I followed the links from the other issue about drone jamming linked to your PR, and just thought I would link some inspiration as a FYI, although you have probably already seen it in the codebase ;-) 

You can use these to add event-handlers to when people activate their radios. (here from my ``XEH_postInit.sqf``)
```sqf
// add eventhandler to radio transmission
// gives params in format: ["_unit", "_radioclass", "_radioType", "_additionalChannel", "_buttonDown"];
[QGVAR(radioTrackingBroadcastLocal), "OnTangent", FUNC(radioTrackingBroadcastLocal), player] call TFAR_fnc_addEventHandler;

// eventhandler for respawn as the TFAR EH we are using is removed upon respawn
player addEventHandler ["Respawn", {
    params ["_unit", "_corpse"];
	// reapply the TFAR eventhandler
    	[QGVAR(radioTrackingBroadcastLocal), "OnTangent", FUNC(radioTrackingBroadcastLocal), _unit] call TFAR_fnc_addEventHandler;
	};
}];
```
You can see how I figure out if LR or SR transmission, radio code and range here: https://github.com/Crowdedlight/Crows-Electronic-Warfare/blob/develop/addons/spectrum/functions/fnc_radioTrackingBroadcastLocal.sqf 

And then do your logic to figure out if they are within range of a sensor truck, and draw a line from player to sensor truck. Landric implemented the line drawing with the spectrum device here: https://github.com/Crowdedlight/Crows-Electronic-Warfare/blob/develop/addons/spectrum/functions/fnc_drawSpectrumLine.sqf

**Comment by b-mayr-1984** [comment]
> Saw this one as I followed the links from the other issue about drone jamming linked to your PR, and just thought I would link some inspiration as a FYI, although you have probably already seen it in the codebase ;-)

Well I definitely intended to shamelessly rip off from your work but I haven't found the time yet to dig into it. 😅

Thanks this summery is very much appreciated and should get me going quicker. 🙂

**Comment by b-mayr-1984** [comment]
Implemented in 67ff55f8a41f270718f3634c0946783d18ff412f

> * [x]  Bearing lines should be visually different to bearing lines from artillery fire (e.g. different color)
> * [x]  Bearings should show up instantly upon triggering the radio (e.g. no delay for the speed of sound)

Such bearings are black and pop up immediately when one presses the TFAR transmit button.
![image](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/76476468/0ab295d4-55ef-4f62-8d53-ac1ea1391de3)

**Comment by b-mayr-1984** [comment]
Tested with @nomisum and @PulsarNeutronStar on a dedicated server. 
Does not work in this environment. 😢 Reopened.

**Comment by Crowdedlight** [comment]
> Tested with @nomisum and @PulsarNeutronStar on a dedicated server. Does not work in this environment. 😢 Reopened.

I don't know what error you had with it, but I had a quick look at the implementation and thought I would mention a few things I noticed. Might not be anything at all, but thought I ought to mention it :)

- I see you add the eventhandlers in ``preinit``. I usually add them in ``postInit`` as I had issue at one point that objects can still be ``null`` in preinit, although not sure if that also is a thing for ``player``. 
- You should be able to just do this, without the extra ``call`` event
```sqf
["arsr_drawData", arsr_fnc_handleDraw] call CBA_fnc_addEventHandler;
```

Although I guess if it worked on hosted, then it sounds like a locality issue instead 😅

**Comment by OverlordZorn** [comment]
https://community.bistudio.com/wiki/Arma_3:_Functions_Library#Config_Levels -> Attributes
CfgFunctions Attributes description.
![grafik](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/56258612/dcd47205-9df1-4799-a6cd-53f9df6b329d)

https://community.bistudio.com/wiki/Initialisation_Order
![grafik](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/assets/56258612/a8c9c65d-3a63-4d38-9238-bf4591febaa0)

It is kind of unclear to me when exactly a player or object is "done initializing" but you can see that pre-init happens before object init and post init after. Anything that calls, which is related to a specific object or object reference like `player` should be post-init.

**Comment by b-mayr-1984** [comment]
### pre- vs. postInit
@Crowdedlight @PulsarNeutronStar I just tested moving the `OnTangent` EH registration from `preInit` to `postInit`. 
It still doesn't work.

### Refactoring
> * You should be able to just do this, without the extra `call` event
> 
> ```sqf
> ["arsr_drawData", arsr_fnc_handleDraw] call CBA_fnc_addEventHandler;
> ```

Correct. Artillery direction finding works with this refactoring as well. Thx 🙂 

### Remaining problem
> Although I guess if it worked on hosted, then it sounds like a locality issue instead 😅

Well... it appears to be.

**Comment by Crowdedlight** [comment]
I had another look. I assume from your message that the normal behaviour with drawing line from sound works, and the markers show up in dedicated? So the ``arsr_drawData`` event gets called. Does the ``arsr_fnc_handleOnTangent`` function fire on radio calls? Was wondering if the problem was that event never being fired, or if its somehow an issue inside ``arsr_fnc_calculate``. 

And here comes the stupid question, are you using TFAR 1.0 Beta? (https://steamcommunity.com/sharedfiles/filedetails/?id=894678801 )  
I have not tried to use ``onTangent`` events in the legacy 0.9 TFAR release. (1.0 has essentially been stable for ages)

**Comment by b-mayr-1984** [comment]
> I had another look. I assume from your message that the normal behaviour with drawing line from sound works, and the markers show up in dedicated?

Correct 

> So the `arsr_drawData` event gets called. Does the `arsr_fnc_handleOnTangent` function fire on radio calls? Was wondering if the problem was that event never being fired, or if its somehow an issue inside `arsr_fnc_calculate`.

I discussed this a bit with @PulsarNeutronStar. I haven't done any tests yet with more debug outputs at the start of certain functions. So I can't yet respond on your questions. But it is on my TODO list.

> And here comes the stupid question, are you using TFAR 1.0 Beta? (https://steamcommunity.com/sharedfiles/filedetails/?id=894678801 ) I have not tried to use `onTangent` events in the legacy 0.9 TFAR release. (1.0 has essentially been stable for ages)

Hm good question. Our server just calls it `@tfar` without further specifying. But the hash in the RPT is `7e7a578334a3bc2122fb67d22fb40345c8293243` if that helps. What is the hash of the TFAR version that you are using?

**Comment by OverlordZorn** [comment]
check your ts tfar version. they're different iirc - if it is `Task Force Arrowhead Radio` 1.-1.0.334 its beta
iirc. the stable is just called task force radio or sth different

**Comment by Crowdedlight** [comment]
> Hm good question. Our server just calls it `@tfar` without further specifying. But the hash in the RPT is `7e7a578334a3bc2122fb67d22fb40345c8293243` if that helps. What is the hash of the TFAR version that you are using?

yeah, my current version of TFAR beta says ``7e7a578334a3bc2122fb67d22fb40345c8293243``. So the versions should be equal. 

And yeah, some debug messages to see what events gets fired would probably show some light on the case. To see where the hold-up are.

**Comment by OverlordZorn** [comment]
in case you wanna have an easier time debugging:

```sqf
_simulationType = switch (true) do {
		case (!isMultiplayer): 				{ "Singleplayer" };
		case (is3DENMultiplayer): 			{ "Editor Multiplayer" };
		case (isMultiplayerSolo): 			{ "Local Hosted Solo" };
		case (isDedicated): 				{ "Dedicated Server" };
		case (isServer && hasInterface): 	{ "Local Hosted" };
		case (hasInterface && !isServer ): 	{ "Player Client" };
		case (!hasInterface && !isServer ): { "Headless Client" };
	};



_str = format ['(debug)(fnc_initPost) player: %1 - SimulationType: %2 - A: %3 - B : %4 - C: %5 -D: %6 -E: %7 -F: %8', player , _simulationType,A ,B,C,D,E,F];

diag_log _str;
if (!isServer) then {	_str remoteExec ["diag_log", 2, false];	};
```
- this Identifies the simulation type (client/server/dedicatedServer etc)
- formulates a _str via format ["...", var,var];
- and if its not on the server, it will remoteExect he string to the server, so it ends up in the server rpt. so you dont have to dig trhough multiple files to figure out whats up

**Comment by dedmen** [comment]
That is neat! That simulation type thing could probably be a CBA function

**Comment by OverlordZorn** [comment]
https://community.bistudio.com/wiki/BIS_fnc_getNetMode

looks like there is something mostly similar already

**Comment by b-mayr-1984** [comment]
And we have another winner thanks to the use of the debugger. 
After c35327dd706ef645e11603c8bf57ef8e6fa96c59 I could make quick work of the problem.
Thx @dedmen 🙂

**Comment by b-mayr-1984** [comment]
Another test with @OverlordZorn on the dedicated server now confirmed it fixed.
