### ISSUE TITLE
shelltracker increasingly broken with time passing

### ISSUE THREAD

**Issue by b-mayr-1984** [gruppe-adler/Shoot_and_Scoot.Tanoa#38]
With increasing time spent in the mission the [shell tracking feature](https://docs.google.com/presentation/d/1BGDOxqqZw4T6js3oQ4mPr4E7f8NLZsPS85MUAAIYvco/edit#slide=id.g27941e9ac27_1_9) shows to be increasingly broken. 
Shells being fired are then not shown in the `systemChat` anymore and also the map markers are not visible.

### Video proof
- [Struwe/Alecandru no Arti tracking](https://www.youtube.com/watch?v=PfVHyE1Ipxg&t=3440s)
- [Struwe showing debug hit message (but no shooting messages)](https://www.youtube.com/watch?v=PfVHyE1Ipxg&t=4756s)
- [Bror showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=wQd9mSkSdfGApC1F&t=5026)
- [Bror showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=iDpvlPykht01kGS2&t=5530)
- [Bestefar showing debug hit message (but no shooting messages)](https://youtu.be/PfVHyE1Ipxg?si=Sozw0JM9-Oroypg6&t=5630)

### Most likely cause
[GetInMan](https://community.bistudio.com/wiki/Arma_3:_Event_Handlers#GetInMan) is described as being _Persistent on respawn if assigned where unit was [local](https://community.bistudio.com/wiki/Multiplayer_Scripting#Locality)_. 
The later is probably not the case, because [fn_postInit.sqf#L6](https://github.com/gruppe-adler/Shoot_and_Scoot.Tanoa/blob/main/scripts/shelltracker/functions/fn_postInit.sqf#L6) makes sure it is assigned where a Zeus is local, not the artillery players.

### Further reading
- https://forums.bohemia.net/forums/topic/190752-event-handler-persist-after-respawn/

**Comment by b-mayr-1984** [comment]
@senshi-x since this is your baby, do you want to take a look at this, or shall I have a look on how to best fix this?

**Comment by senshi-x** [comment]
Will take a look.
